In [17]:
import csv
import numpy as np
import pandas as pd

# Pasar la BBDD a una lista
v_bbdd = []
count = 0

with open('bbdd_primitiva.csv') as f:
    reader = csv.reader(f, delimiter = '\t')
    for row in reader:
        if count != 0:
            linea = row[1:]

            tablero = [
                [linea[0], linea[1], linea[2]],
                [linea[3], linea[4], linea[5]],
                [linea[6], linea[7], linea[8]]
            ]

            v_bbdd.append(tablero)
            v_bbdd.append(np.fliplr(tablero))
            v_bbdd.append(np.flipud(tablero))
            v_bbdd.append(np.fliplr(np.flipud(tablero)))
            v_bbdd.append(np.rot90(tablero))
            v_bbdd.append(np.fliplr(np.flipud(np.rot90(tablero))))
            v_bbdd.append(np.flipud(np.rot90(tablero)))
            v_bbdd.append(np.fliplr(np.rot90(tablero)))

        count += 1

# print (v_bbdd, dt.byteorder)

# from sklearn.utils import shuffle
# v_bbdd = pd.DataFrame(shuffle(v_bbdd))
v_bbdd = pd.DataFrame(v_bbdd)

# bbdd.head()
v_bbdd

             0          1          2
0    [0, 0, 0]  [0, 2, 0]  [0, 0, 0]
1    [0, 0, 0]  [0, 2, 0]  [0, 0, 0]
2    [0, 0, 0]  [0, 2, 0]  [0, 0, 0]
3    [0, 0, 0]  [0, 2, 0]  [0, 0, 0]
4    [0, 0, 0]  [0, 2, 0]  [0, 0, 0]
..         ...        ...        ...
171  [0, 0, 2]  [0, 1, 0]  [0, 0, 2]
172  [0, 0, 0]  [0, 1, 0]  [2, 0, 2]
173  [2, 0, 2]  [0, 1, 0]  [0, 0, 0]
174  [2, 0, 2]  [0, 1, 0]  [0, 0, 0]
175  [0, 0, 0]  [0, 1, 0]  [2, 0, 2]

[176 rows x 3 columns]

In [1]:
v_bbdd.to_csv('bbdd.csv')

NameError: name 'v_bbdd' is not defined

In [4]:
from pandas import *
import numpy as np

v_tab = np.array([['a', 'b', 'c'],
                  ['d', 'e', 'f'],
                  ['g', 'h', 'i']])

print (DataFrame(v_tab))
print ()
print ('Tabla al revés')
print (np.fliplr(v_tab))
print ()
print ('Tabla bocabajo')
print (np.flipud(v_tab))
print ()
print ('Tabla bocabajo y al revés')
print (np.fliplr(np.flipud(v_tab)))
print ()
print ('Tabla rotación 90º sentido antihorario')
print (np.rot90(v_tab))
print ()
print ('Tabla rotación 90º sentido horario')
print (np.fliplr(np.flipud(np.rot90(v_tab))))
print ()
print ('Tabla ordenada por columnas')
print (np.flipud(np.rot90(v_tab)))
print ()
print ('Tabla rotación 90º sentido antihorario al revés')
print (np.fliplr(np.rot90(v_tab)))

   0  1  2
0  a  b  c
1  d  e  f
2  g  h  i

Tabla al revés
[['c' 'b' 'a']
 ['f' 'e' 'd']
 ['i' 'h' 'g']]

Tabla bocabajo
[['g' 'h' 'i']
 ['d' 'e' 'f']
 ['a' 'b' 'c']]

Tabla bocabajo y al revés
[['i' 'h' 'g']
 ['f' 'e' 'd']
 ['c' 'b' 'a']]

Tabla rotación 90º sentido antihorario
[['c' 'f' 'i']
 ['b' 'e' 'h']
 ['a' 'd' 'g']]

Tabla rotación 90º sentido horario
[['g' 'd' 'a']
 ['h' 'e' 'b']
 ['i' 'f' 'c']]

Tabla ordenada por columnas
[['a' 'd' 'g']
 ['b' 'e' 'h']
 ['c' 'f' 'i']]

Tabla rotación 90º sentido antihorario al revés
[['i' 'f' 'c']
 ['h' 'e' 'b']
 ['g' 'd' 'a']]

In [2]:
#COPIA DE SEGUREDAD

from pandas import *
import numpy as np

v_tab = np.array([['a', 'b', 'c'],
                  ['d', 'e', 'f'],
                  ['g', 'h', 'i']])

print (DataFrame(v_tab))
print ('')
print ('Primera fila:')
print (v_tab[0,:])
print ('Segunda fila:')
print (v_tab[1,:])
print ('Tercera fila:')
print (v_tab[2,:])
print ('')
print ('Primera columna:')
print (v_tab[:,0])
print ('Segunda columna:')
print (v_tab[:,1])
print ('Tercera columna:')
print (v_tab[:,2])
print ('')
print ('Diagonal izquierda arriba -> derecha abajo')
print (v_tab.diagonal())
print ('Diagonal derecha arriba -> izquierda abajo')
print (np.fliplr(v_tab).diagonal())
print ('Diagonal izquierda abajo -> derecha arriba')
print (np.flipud(v_tab))
print ('Diagonal derecha abajo -> izquierda arriba')


print (np.flipud(v_tab))

   0  1  2
0  a  b  c
1  d  e  f
2  g  h  i

Primera fila:
['a' 'b' 'c']
Segunda fila:
['d' 'e' 'f']
Tercera fila:
['g' 'h' 'i']

Primera columna:
['a' 'd' 'g']
Segunda columna:
['b' 'e' 'h']
Tercera columna:
['c' 'f' 'i']

Diagonal izquierda arriba -> derecha abajo
['a' 'e' 'i']
Diagonal derecha arriba -> izquierda abajo
['c' 'e' 'g']
Diagonal izquierda abajo -> derecha arriba
[['g' 'h' 'i']
 ['d' 'e' 'f']
 ['a' 'b' 'c']]
Diagonal derecha abajo -> izquierda arriba
[['g' 'h' 'i']
 ['d' 'e' 'f']
 ['a' 'b' 'c']]